<?php

namespace App\Utils;

class FakeProduct
{
    public static function fake(): array
    {
        $properties = [
            [
                "category_id" => 9,
                "title" => null,
                "slug" => "bien-en-vente-1",
                "excerpt" => null,
                "content" => null,
                "address" => null,
                "client_address" => null,
                "type" => "BIEN EN VENTE",
                "price" => 5000000,
                "deposit_price" => null,
                "price_second" => 25000,
                "location_id" => 1,
                "unlisted_city" => null,
                "location_description" => "brofodoumeekro",
                "video_link" => null,
                "latitude" => null,
                "longitude" => null,
                "created_by" => 1,
                "updated_by" => 1,
                "periodicity" => null,
                "bathrooms" => 0,
                "bedrooms" => null,
                "garages" => null,
                "kitchens" => 0,
                "rooms" => null,
                "area" => "500",
                "area_unit" => "M",
                "area_count" => 1,
                "count_advance" => null,
                "count_monthly" => 0,
                "jacuzzi" => 0,
                "bath" => 0,
                "WiFi" => 0,
                "pool" => 0,
                "air_conditioning" => 0,
                "acd" => 0,
                "site_approved" => 1,
                "home_type" => null,
                "home_type_more" => null,
                "security" => null,
                "purchase_power" => null,
                "accessibility" => null,
                "status" => "PUBLISH",
                "total_click" => 0,
            ],
            [
                "id" => 2,
                "category_id" => 1,
                "title" => null,
                "slug" => "location-2",
                "excerpt" => null,
                "content" => null,
                "address" => null,
                "client_address" => null,
                "type" => "LOCATION",
                "price" => 250000,
                "deposit_price" => null,
                "price_second" => null,
                "location_id" => 1,
                "unlisted_city" => null,
                "location_description" => "CIE",
                "video_link" => null,
                "latitude" => null,
                "longitude" => null,
                "created_by" => 1,
                "updated_by" => 1,
                "periodicity" => "MONTH",
                "bathrooms" => 1,
                "bedrooms" => null,
                "garages" => null,
                "kitchens" => 2,
                "rooms" => null,
                "area" => "0",
                "area_unit" => "M",
                "area_count" => null,
                "count_advance" => null,
                "count_monthly" => 0,
                "jacuzzi" => 0,
                "bath" => 0,
                "WiFi" => 0,
                "pool" => 0,
                "air_conditioning" => 0,
                "acd" => 0,
                "site_approved" => 0,
                "home_type" => "Studio",
                "home_type_more" => null,
                "security" => "WITH_GUARD",
                "purchase_power" => "LESS_EXPENSIVE",
                "accessibility" => "NOT_FAR_FROM_THE_TAR",
                "status" => "PUBLISH",
                "total_click" => 0,
            ],
            [
                "id" => 3,
                "category_id" => 7,
                "title" => null,
                "slug" => "reservation-3",
                "excerpt" => null,
                "content" => null,
                "address" => null,
                "client_address" => null,
                "type" => "RESERVATION",
                "price" => 350000,
                "deposit_price" => null,
                "price_second" => null,
                "location_id" => 1,
                "unlisted_city" => null,
                "location_description" => "Macory",
                "video_link" => null,
                "latitude" => null,
                "longitude" => null,
                "created_by" => 1,
                "updated_by" => 1,
                "periodicity" => "DAY",
                "bathrooms" => 0,
                "bedrooms" => null,
                "garages" => null,
                "kitchens" => 0,
                "rooms" => null,
                "area" => "0",
                "area_unit" => "M",
                "area_count" => null,
                "count_advance" => null,
                "count_monthly" => 0,
                "jacuzzi" => 1,
                "bath" => 1,
                "WiFi" => 1,
                "pool" => 1,
                "air_conditioning" => 1,
                "acd" => 0,
                "site_approved" => 0,
                "home_type" => "2 pièces",
                "home_type_more" => null,
                "security" => null,
                "purchase_power" => null,
                "accessibility" => null,
                "status" => "PUBLISH",
                "total_click" => 0,
            ],
            [
                "category_id" => "1",
                "slug" => "bien-en-vente-4",
                "type" => "BIEN EN VENTE",
                "price" => 550000,
                "location_id" => "1",
                "location_description" => "Danga",
                "created_by" => "1",
                "updated_by" => "1",
                "bathrooms" => 0,
                "kitchens" => 0,
                "area" => "500",
                "area_unit" => "M",
                "home_type" => "Villa",
                "status" => "PUBLISH",
            ], [
                "category_id" => "8",
                "slug" => "reservation-5",
                "type" => "RESERVATION",
                "price" => 250000,
                "location_id" => "1",
                "location_description" => "CIE",
                "created_by" => "1",
                "updated_by" => "1",
                "bathrooms" => 0,
                "kitchens" => 0,
                "jacuzzi" => 1,
                "air_conditioning" => 1,
                "home_type" => "Chambre",
                "status" => "PUBLISH",
            ],
            [
                "category_id" => "1",
                "slug" => "location-6",
                "type" => "LOCATION",
                "price" => 175000,
                "location_id" => "1",
                "location_description" => "Aras",
                "created_by" => "1",
                "updated_by" => "1",
                "bathrooms" => 1,
                "kitchens" => 1,
                "area" => "250",
                "area_unit" => "M",
                "home_type" => "2 pièces",
                "status" => "PUBLISH",
            ],
            [
                "category_id" => "7",
                "slug" => "reservation-7",
                "type" => "RESERVATION",
                "price" => 1250000,
                "location_id" => "1",
                "location_description" => "CIE",
                "created_by" => "1",
                "updated_by" => "1",
                "jacuzzi" => 1,
                "air_conditioning" => 1,
                "home_type" => "Studio",
                "status" => "PUBLISH",
            ],
        ];

        return $properties;
    }
}
