name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd client_nextjs
          npm install

      - name: Build app
        run: |
          cd client_nextjs
          npm run build

    #   - name: Deploy to hosting service
    # Add your deployment steps here, like deploying to Vercel, Netlify, etc.
